# Generated by Django 6.0.3 on 2026-04-03 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Warehouse Manchester', max_length=200)),
                ('postcode', models.CharField(max_length=10)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('industry_type', models.CharField(choices=[('warehouse', 'Warehouse / Distribution'), ('supermarket', 'Supermarket / Retail'), ('industrial', 'Industrial / Manufacturing'), ('data_centre', 'Data Centre'), ('community', 'Community Energy'), ('other', 'Other')], default='warehouse', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
