# Generated by Django 6.0.6 on 2026-06-22 19:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GridEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('DFS', 'Demand Flexibility Service'), ('ENWL', 'ENWL')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(default='upcoming', max_length=20)),
                ('reward_gbp_per_mwh', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindForecast',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('forecast_mw', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('price_gbp_per_mwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price_type', models.CharField(choices=[('wholesale', 'Wholesale'), ('day_ahead', 'Day-Ahead')], max_length=50)),
            ],
            options={
                'unique_together': {('timestamp', 'price_type')},
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=20)),
                ('industry_type', models.CharField(choices=[('MANUFACTURING', 'Manufacturing'), ('FOOD_PROCESSING', 'Food Processing'), ('RETAIL', 'Retail / Supermarket'), ('WAREHOUSE', 'Warehouse / Logistics'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('flexible_loads', models.TextField(blank=True, null=True)),
                ('temp_min_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-20)])),
                ('temp_max_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(50)])),
                ('shift_notice_hours', models.PositiveIntegerField(default=2)),
                ('max_shift_duration_hours', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OptimizationRecommendation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('action_type', models.CharField(max_length=100)),
                ('recommended_kwh_shift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_savings_gbp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('reasoning', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='dashboard.site')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff')], default='CUSTOMER', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('consumption_kwh', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('export_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('meter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('data_source', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV'), ('api', 'API')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='dashboard.site')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['site', 'timestamp'], name='dashboard_m_site_id_d124e8_idx'), models.Index(fields=['timestamp'], name='dashboard_m_timesta_088de3_idx')],
                'unique_together': {('site', 'timestamp')},
            },
        ),
    ]
