# Generated by Django 6.0.6 on 2026-06-19 22:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GridEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('DFS', 'Demand Flexibility Service'), ('ENWL', 'ENWL')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(default='upcoming', max_length=20)),
                ('reward_gbp_per_mwh', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindForecast',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('forecast_mw', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='max_shift_duration_hours',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='site',
            name='shift_notice_hours',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='site',
            name='temp_max_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='site',
            name='temp_min_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-20)]),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('user', 'name')},
        ),
        migrations.CreateModel(
            name='EnergyPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('price_gbp_per_mwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price_type', models.CharField(choices=[('wholesale', 'Wholesale'), ('day_ahead', 'Day-Ahead')], max_length=50)),
            ],
            options={
                'unique_together': {('timestamp', 'price_type')},
            },
        ),
        migrations.CreateModel(
            name='OptimizationRecommendation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('action_type', models.CharField(max_length=100)),
                ('recommended_kwh_shift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_savings_gbp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('reasoning', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='dashboard.site')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff')], default='CUSTOMER', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('consumption_kwh', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('export_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('meter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('data_source', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV'), ('api', 'API')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='dashboard.site')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['site', 'timestamp'], name='dashboard_m_site_id_d124e8_idx'), models.Index(fields=['timestamp'], name='dashboard_m_timesta_088de3_idx')],
                'unique_together': {('site', 'timestamp')},
            },
        ),
    ]
